#pragma once

#define NAME_OF_INIFILE		L"mklog"	//iniファイル名
#define EXT_OF_INIFILE		L"ini"		//iniファイル拡張子


#define PATH_SECT_OF_INIFILE				L"PATH1"		//ファルダパスセクション
#define SET_SECT_OF_INIFILE					L"SET"			//機能パラメータセクション
#define DATA_TYPE1_SECT_OF_INIFILE			L"DATA_TYPE1"	//記録データのタイプ　0:double 1:int 2:bool
#define LABEL_NAME1_SECT_OF_INIFILE			L"LABEL1"		//ログデータラベルセクション
#define DATA_TYPE2_SECT_OF_INIFILE			L"DATA_TYPE2"	//記録データのタイプ　0:double 1:int 2:bool
#define LABEL_NAME2_SECT_OF_INIFILE			L"LABEL2"		//ログデータラベルセクション			L"DATA_TYPE1"	//記録データのタイプ　0:double 1:int 2:bool
#define DATA_TYPE3_SECT_OF_INIFILE			L"DATA_TYPE3"	//記録データのタイプ　0:double 1:int 2:bool
#define LABEL_NAME3_SECT_OF_INIFILE			L"LABEL3"		//ログデータラベルセクション

#define PATH1_LOG1_KEY_OF_INIFILE			L"LOG_PATH1"

#define SET_NUM_OF_LOGS_KEY_OF_INIFILE		L"N_LOGs"

#define SET_LOGNAME1_KEY_OF_INIFILE			L"LOG_NAME1"
#define SET_LOGTYPE1_KEY_OF_INIFILE			L"LOG_TYPE1"
#define SET_SAMPLE_TIME1_KEY_OF_INIFILE		L"SAMPLING_ms1"
#define SET_ITME_NUM1_KEY_OF_INIFILE		L"N_ITEMs1"
#define SET_ITME_TIMESET1_KEY_OF_INIFILE	L"TIMESET1"
#define SET_LOGNAME2_KEY_OF_INIFILE			L"LOG_NAME2"
#define SET_LOGTYPE2_KEY_OF_INIFILE			L"LOG_TYPE2"
#define SET_SAMPLE_TIME2_KEY_OF_INIFILE		L"SAMPLING_ms2"
#define SET_ITME_NUM2_KEY_OF_INIFILE		L"N_ITEMs2"
#define SET_ITME_TIMESET2_KEY_OF_INIFILE	L"TIMESET2"
#define SET_LOGNAME3_KEY_OF_INIFILE			L"LOG_NAME3"
#define SET_LOGTYPE3_KEY_OF_INIFILE			L"LOG_TYPE3"
#define SET_SAMPLE_TIME3_KEY_OF_INIFILE		L"SAMPLING_ms3"
#define SET_ITME_NUM3_KEY_OF_INIFILE		L"N_ITEMs3"
#define SET_ITME_TIMESET3_KEY_OF_INIFILE	L"TIMESET3"

#define LABEL01_KEY_OF_INIFILE			L"LABEL01"
#define LABEL02_KEY_OF_INIFILE			L"LABEL02"
#define LABEL03_KEY_OF_INIFILE			L"LABEL03"
#define LABEL04_KEY_OF_INIFILE			L"LABEL04"
#define LABEL05_KEY_OF_INIFILE			L"LABEL05"
#define LABEL06_KEY_OF_INIFILE			L"LABEL06"
#define LABEL07_KEY_OF_INIFILE			L"LABEL07"
#define LABEL08_KEY_OF_INIFILE			L"LABEL08"
#define LABEL09_KEY_OF_INIFILE			L"LABEL09"
#define LABEL10_KEY_OF_INIFILE			L"LABEL10"


#define TYPE01_KEY_OF_INIFILE			L"TYPE01"
#define TYPE02_KEY_OF_INIFILE			L"TYPE02"
#define TYPE03_KEY_OF_INIFILE			L"TYPE03"
#define TYPE04_KEY_OF_INIFILE			L"TYPE04"
#define TYPE05_KEY_OF_INIFILE			L"TYPE05"
#define TYPE06_KEY_OF_INIFILE			L"TYPE06"
#define TYPE07_KEY_OF_INIFILE			L"TYPE07"
#define TYPE08_KEY_OF_INIFILE			L"TYPE08"


